#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

wmake src/functionObjects/performance
wmake src/functionObjects/lossCoefficient

wmake application/lusgsFoam

# -----------------------------------------------------------------------------
