#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication fluent3DMeshToFoam radiver.msh

runApplication changeDictionary

runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar
